# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.BigIntegerField()),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('answer4', models.TextField()),
                ('answer5', models.TextField()),
                ('answer6', models.TextField()),
                ('answer7', models.TextField()),
                ('answer8', models.TextField()),
                ('answer9', models.TextField()),
                ('answer10', models.TextField()),
            ],
        ),
    ]
